### ISSUE TITLE
Some Hunter themes have unreadable diagnostics for warnings

### ISSUE THREAD

**Issue by rgbkrk** [teziovsky/zed-one-hunter-theme#1]
Vercel:

![image](https://github.com/teziovsky/zed-one-hunter-theme/assets/836375/b7745797-ecef-4857-98e5-1b0f39f2e1ce)

Material:

![image](https://github.com/teziovsky/zed-one-hunter-theme/assets/836375/18fb1bba-527f-4e2d-9677-1747fd024229)

**Comment by teziovsky** [comment]
I know those bugs. There are some similar bugs with colors 🤔 When I will have a bunch of free time, I'll try to fix it 😎

**Comment by rgbkrk** [comment]
Thanks!

**Comment by teziovsky** [comment]
Fixes are waiting for merge:
https://github.com/zed-industries/extensions/pull/674
If you have any advice, just tell me 😎 Otherwise please close this issue 🫶🏼

**Comment by rgbkrk** [comment]
It's working, thanks for this theme! 

![image](https://github.com/teziovsky/zed-one-hunter-theme/assets/836375/add26e73-d304-4e25-927a-d3f1518a95b5)

I'm not a superfan of the colors used, but this'll do.

**Comment by teziovsky** [comment]
Those are used only just to fix this problem. I wanted that theme to be useful for you asap. When I will have more free time, then I will customize that themes to match other colors 😎

**Comment by rgbkrk** [comment]
Love it, thank you. I switched right back to your theme after you fixed it. Thanks!
